export const CONVERT_TO_EUR = 'CONVERT_TO_EUR';
export const CONVERT_TO_PLN = 'CONVERT_TO_PLN';

export const ADD_TRANSACTION = 'ADD_TRANSACTION';
export const INIT_TRANSACTIONS = 'INIT_TRANSACTIONS';
export const REMOVE_TRANSACTION = 'REMOVE_TRANSACTION';
export const SORT_TRANSACTIONS = 'SORT_TRANSACTIONS';

export const GET_CURRENCY = 'GET_CURRENCY';
